### ISSUE TITLE
App size become huge

### ISSUE THREAD

**Issue by amiteshsinghkundan** [twilio/twilio-conversations-demo-kotlin#36]
![image](https://user-images.githubusercontent.com/97089194/157616991-2d096892-3e4d-4fb2-bfcd-e2ad1d9fefe0.png)
![image](https://user-images.githubusercontent.com/97089194/157617116-349cfae9-9f1b-4580-b7c2-7c8622cf270a.png)
![image](https://user-images.githubusercontent.com/97089194/157617184-32800df4-c0cc-4672-be0d-e939ddd51985.png)
Hi..
After integration of twilio conversation sdk app size becomes 627 mb before integration its about 70-85 mb.  
implementation "com.twilio:conversations-android-with-symbols:3.0.0"

**Comment by rusmonster** [comment]
Hi!
1. If you don't need native symbols in order to upload to crashlytics or similar service - just use the sdk version without symbols:
```
com.twilio:conversations-android:3.0.0
```

2. If you need symbols - you should [setup android NDK](https://developer.android.com/studio/projects/install-ndk) in your app correctly in order to make gradle be able to strip symbols.
